### ISSUE TITLE
Error in initSimulation(XML = simModelXML, whichInitParam = "none") : Unknown Error

### ISSUE THREAD

**Issue by mark0935git** [Open-Systems-Pharmacology/R-Toolbox#15]
I have installed the latest version of R-toolbox 7.1 under R v3.3.3 environment.

I constantly met the same same error, when I tried to test my installation using R-Toolbox/tests/01_microtest.R script

After loading the model file, the initSimulation command gave the following error message:

standard_dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")
Error in initSimulation(XML = simModelXML, whichInitParam = "none") : 
  Unknown Error 
in SimModelComp_XMLHelper::XMLStringFromFile

**Comment by msevestre** [comment]
Have you installed the OSPSuite as well?

**Comment by mark0935git** [comment]
Yes! I did installed the OSPSsuite, PKSim, and Mobi. Are any other packages required? Ruby?

**Comment by Yuri05** [comment]
No other packages required.

Please **restart R** and execute the code below (replace model xml path with yours).
Does it execute as expected or do you get any errors?

```
require(MoBiToolboxForR)
simModelXML <- "C:/temp/S1.xml"
dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")
dci_info <- processSimulation(DCI_Info = dci_info)

```

**Comment by mark0935git** [comment]
Thanks a lot for your help! I have reinstalled everything from scratch and tried the commands.

I used 'black american girl.xml' and 'PopSim.xml' in the test examples to replace the 'C:/temp/S1.xml' , as the file does not exist on my PC.

It still gives the same error as shown below. I wild guess is that there might be an error in the model reader in the new release. It does not read the previous model properly,

Error in initSimulation(XML = simModelXML, whichInitParam = "none") : 
  Unknown Error 
in SimModelComp_XMLHelper::XMLStringFromFile

**Comment by Yuri05** [comment]
>I wild guess is that there might be an error in the model reader in the new release. It does not read the previous model properly

No :-) This works pretty fine.

I guess the problem is a download function of GitHub. If you downloaded those xml files via **SaveAs** function in your browser, it's not the xml file but some kind of html what is being saved.
(You can verify it by opening a downloaded file in any text editor.)

Instead of using **SaveAs**, you should just click on an xml file and use a **Download** button.
After that model should be loaded properly in the R-toolbox.

(What could be improved for sure is the error message if trying to load a non-xml file :-)

<img width="679" alt="unbenannt" src="https://user-images.githubusercontent.com/25061876/26921567-c055808e-4c3c-11e7-87b1-9de830359c5a.png">

**Comment by mark0935git** [comment]
Yes, the error has been solved by downloading the xml file using the **Download** button. 
Thanks a lot for your help! The case can be closed now.
