### ISSUE TITLE
Run R Unit tests on CI 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/R-Toolbox#35]
Apparently there are Unit tests in R!! Woot woot. But...we are not running them before creating the package which is not so great.

An awesome feature would be to be able to run those tests via command line from the CI Server. 
Right now we are performing quite a bunch of stuff to package the code into an R package etc.. 
Especially we have to install 
 * R
 * R Tools. 

Is there a way to run those unit tests ? A simple command line would be enough. 

The appveyor script could be updated to run all tests upon commit and would fail if one or more test is failing. 

Anyone?

**Comment by msevestre** [comment]
Now I am just seeing that some tests are relying on absolute path! 
https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/tests/01_microtest.R#L9

Big no no if we want to run them on CI. This needs to become dynamic

**Comment by PavelBal** [comment]
> Apparently there are Unit tests in R!! Woot woot.

🤣 

> Is there a way to run those unit tests ? A simple command line would be enough.

https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/tests/DoRUnitTesting.R

runs all the tests and creates a report html. However, the path to test files is hard coded, and the script loads the compiled toolbox - should be probably changed to use the source files instead of the package (https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/develop/tests/SourceCodeFiles.R seems to do this..)?

The 01_microtest.R is not used (at least not to my knowledge). Only files starting with "runit." are executed. So what should be done is probably re-writing DoRUnitTesting.R and SourceCodeFiles.R to use CLI provided path instead of hard-coded string.

> The appveyor script could be updated to run all tests upon commit and would fail if one or more test is failing.

Well, then we won't be having an R-Toolbox right now, because some tests are failing :)

**Comment by msevestre** [comment]
>Well, then we won't be having an R-Toolbox right now, because some tests are failing :)

Are you saying that some tests (even when path are adjusted etc..) are failing??

@PavelBal do you know if this is possible to run an R script from a command line
Say R.exe run <path_to_file.R> and get a 1 or 0 as a return value that would let us know if the tests are failing or not? 
We could redirect the standard output in appveyor to see the failing tests... just some random ideas here.

**Comment by PavelBal** [comment]
Yes, some tests are failing - among them the test for setSimulationTime.

It is definitely possible to run scrips from the CMD - I will play around with DoRUnitTesting.R and see how a feedback can be implemented.

**Comment by msevestre** [comment]
@PavelBal Awesome

**Comment by PavelBal** [comment]
Calling DoRUnitTesting.R will do the following:
1) Performs the tests
2) Print some output to the console (see screenshot below)
3) Create a "Protocol.html" with details on the results
4) Return an integer representing the number of errors/fails. I.e., everything not 0 means that some test fail.

![image](https://user-images.githubusercontent.com/25903040/35377201-897a8a0a-01ae-11e8-9068-782d39bb0fd5.png)


Is this the anticipated workflow?
