### ISSUE TITLE
saveSimulationToXML() cannot write "µ" properly.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/R-Toolbox#54]
Saved XML-files contain "ﾵ" instead of "µ".

**Comment by Yuri05** [comment]
"ﾵ" looks much better ;-)

To avoid this, _saveSimulationToXML_ should be changed: instead of calling 
`retval = .Call('RDCI_Invoke', DCI_Info$Handle, 'SaveSimulationToXml', XML);`

it should get a simulation XML string via
`simulationXMLString = .Call('RDCI_Invoke', DCI_Info$Handle, 'GetSimulationString', '');`

and save it into a xml file using UTF-8 Encoding

([s. Matlab code of _saveSimulationToXML_](https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox-Core/blob/be5e39f109d4625fef6985a17e395d80655ac0d2/code/saveSimulationToXML.m#L48))

**Comment by PavelBal** [comment]
Great, thanks.

Can you point me to the code from which DCIR is compiled?

**Comment by Yuri05** [comment]
The problem is in [saveSimulationToXML.R#L35](https://github.com/Open-Systems-Pharmacology/R-Toolbox/blob/9d8655dbea3106011c93d986e414e2d159ab2476/src/code/saveSimulationToXML.R#L35)

DCIR is just a common data transfer interface between R and C++.

If you are interested in how those DCIR calls are handled, you might check it here:
* [_saveSimulationToXML_](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/src/OSPSuite.SimModelComp/src/SimModelComp.cpp#L1280)
* [_GetSimulationString_](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/src/OSPSuite.SimModelComp/src/SimModelComp.cpp#L1300)

**Comment by PavelBal** [comment]
> If you are interested in how those DCIR calls are handled, you might check it here:

Exactly, thank you!

**Comment by PavelBal** [comment]
Just curious - why is the workaround

```
		//just writing std::string to file destroys UTF8 encoding
		//implemented workaround via wstring as found here: 
		//http://mariusbancila.ro/blog/2008/10/20/writing-utf-8-files-in-c/

		wstring wstr(str.begin(), str.end());
		string utf8string = to_utf8(wstr);
		outf << utf8string;
```

in [SimModelComp_XMLHelper.cpp](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/src/OSPSuite.SimModelComp/src/SimModelComp_XMLHelper.cpp#L242) not working around? :)

**Comment by Yuri05** [comment]
A am also curious why...

**Comment by PavelBal** [comment]
Fixed in SimModel.
