### ISSUE TITLE
Problems with parenthesis in paths

### ISSUE THREAD

**Issue by AnneGrimbs** [Open-Systems-Pharmacology/R-Toolbox#55]
When extracting my simulation results an error is raised that the path of my output would not exist, however, the path is exactly the one from the corresponding XML file:
 
`
Error in getSimulationResult(path_id = outputs[k], DCI_Info = dci_info) : 
  Result with path_id 5mg/kg Male - all|Organism|Liver|Compound1|Tissue (Liver) does not exist!
`

Observer in XML file
`    <Observer id="15625" entityId="bQMi_zFotESwJqmYAm36Yw" name="Tissue (Liver)" path="5mg/kg Male - all|Organism|Liver|Compound1|Tissue (Liver)" unit="µmol/l" persistable="1" formulaId="16917" />
`

This problem only occurs for paths that contain a parenthesis, so far. As soon as I modify the corresponding path in the XML file to:
`    <Observer id="15625" entityId="bQMi_zFotESwJqmYAm36Yw" name="Tissue (Liver)" path="5mg/kg Male - all|Organism|Liver|Compound1|Tissue Liver" unit="µmol/l" persistable="1" formulaId="16917" />
`
everything works well.

Could you, please, check what is the problem... especially as the observer I used is a predefined one in MoBi.

**Comment by PavelBal** [comment]
Yes, it is a known problem and will be fixed in the next release. Actually, the "develop"-branch of the toolbox already includes the fix, so you could (unofficially) download the source files

https://github.com/Open-Systems-Pharmacology/R-Toolbox/tree/develop/src

and use them instead of the original included in the package. If you are willing to take the risk (not much of a risk to my judgment), you have to source the downloaded R-files after loading the MoBiToolboxForR package:

```
library(MoBiToolboxForR)
    #Source all code files of the toolbox.
    rfiles <- dir(pathToThe_src_folder, pattern = "*.R")
    for (i in 1:length(rfiles)) {
        rfile <- file.path(srcFolderDir, rfiles[i])
        if (!(file.info(rfile)$isdir)) {
            source(rfile)
        }
    }
```

Otherwise, a workaround is to use '\\\\(' and '\\\\)' instead of '(' and ')'. But be cautious because the "workaround" will lead to errors in the next official release!

**Comment by PavelBal** [comment]
Already fixed, please close.
